### ISSUE TITLE
View headers button does not function

### ISSUE THREAD

**Issue by Xalaxis** [BeatPlus/Protonmail#46]
Clicking the 'view headers' button does not open the headers as expected

![image](https://cloud.githubusercontent.com/assets/12937964/18810727/618d292e-8295-11e6-9057-54c194ac79ef.png)

(Maybe hook the new tab into a popup window?)

**Comment by BeatPlus** [comment]
I need to investigate this issue, but I cannot promise anything in the short-run. Can you provide some more info? Does it open the link in your default browser or just does nothing?

**Comment by Xalaxis** [comment]
It just does nothing.

**Comment by BeatPlus** [comment]
This bug is caused by the singleinstance parameter set to the electron window. When clicking a button that opens a new window, instead of allowing creating a new electron instance, it either opens it externally or just does not perform anything.
I will give it a try playing with the singleinstance code.

**Comment by kontrollanten** [comment]
this should be considered as semi fixed since #111 merge. Semi by the meaning that it will open up a new window and load the URL, but the Protonmail loader wont stop spinning. I assume this is some kind of security check by Protonmail. If you've got any idea how this could be solved, feel free to open this up again.
