### ISSUE TITLE
Stay logged in

### ISSUE THREAD

**Issue by cryptono** [BeatPlus/Protonmail#57]
Hi,
this is a great project. But it is a shame that I must relogin after closing the app.
Maybe the webapp could safe the login data and automatically execute the login button at startup?
Thanks!

**Comment by HaydenSD** [comment]
We *could*, although the problem is that Protonmail is about security and this feature would drastically lessen it.

**Comment by BeatPlus** [comment]
There could be a way to do it, but in terms of security is a no. Not even the protonmail website allows you to save sessions through cookies.

**Comment by alexanderadam** [comment]
The [ProtonMail Bridge](https://protonmail.com/default/bridge/) also gives a possibility not having to sign in every time.
It is acting like a local SMTP server.

You also don't have to provide your 2FA credentials again.
Thus `unofficial-protonmail-desktop` is trying to be more secure than Protonmail's own tools here, since the architecture ProtonMail Bridge is also only secure as long the system where it's running on is not compromised / its storage is not accessible by third parties.

So maybe you want to reconsider fixing this issue?
